#컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#       Compilador DIV
#컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

EXE=div_stub.exe

#OPTIONS=/oneatx /wx /mf /zp4 /bt=dos /5r /fp5
#OPTIONS2=/oneatx /wx /mf /zp4 /bt=dos /5r /fp5

#Release
#OPTIONS=/oneatx /wx /mf /zp4 /bt=dos /5r /fp5 /i=div_stub /i=netlib /i=vpe /i=source /i=inc /i=judas

#Debug
#OPTIONS=/d2 /wx /mf /zp4 /bt=dos /5r /fp5 /i=div_stub /i=netlib /i=vpe /i=source /i=inc /i=judas

OPTIONS=/oneatx /wx /mf /zp4 /bt=dos /5r /fp5

$(EXE): div_stub.obj

  wlink @div_stub.lnk

div_stub.obj: div_stub.cpp
  wcc386 $(OPTIONS) div_stub.cpp
