language: minimal
dist: focal
jobs:
  include:
    - os: windows
      env:
        WATCOM: $HOME/watcom
        PATH: $WATCOM/binnt:$WATCOM/binw:$PATH
        INCLUDE: $WATCOM/h
        EDPATH: $WATCOM/eddat
        WIPFC: $WATCOM/wipfc
        LIB: $WATCOM/lib286:$WATCOM/lib286/dos:$WATCOM/lib386:$WATCOM/lib386/dos
        DOSBOX: $HOME/dosbox-x/dosbox-x.exe
    - os: linux
      env:
        WATCOM: $HOME/watcom
        PATH: $WATCOM/binl:$WATCOM/binw:$PATH
        INCLUDE: $WATCOM/h
        EDPATH: $WATCOM/eddat
        WIPFC: $WATCOM/wipfc
        LIB: $WATCOM/lib286:$WATCOM/lib286/dos:$WATCOM/lib386:$WATCOM/lib386/dos
        DOSBOX: $HOME/dosbox-x/bin/dosbox-x

before_install:
  - .travis/install_watcom.sh
  - .travis/install_dosbox.sh
script:
  - wmake
  - wmake tools
  - wmake test DOSBOX=$DOSBOX
cache:
  directories:
    - ~/watcom
    - ~/dosbox-x
