#ifndef __ANIM_ANMS_
#define __ANIM_ANMS_

#define FRAME0  1

#define	ANIM_GOLPE		0
#define	ANIM_ANDAR		1
#define	ANIM_ANDAR2		2
#define	ANIM_CORRER		3
#define	ANIM_AGACHAR		4
#define	ANIM_IMPACTO		5
#define	ANIM_IMPACTO2		6
#define	ANIM_MARCHA		7
#define	ANIM_MORTAL		8
#define	ANIM_MUERTE		9
#define	ANIM_NEGACION		10
#define	ANIM_PATADA		11
#define	ANIM_PATADA2		12
#define	ANIM_PATADA3		13
#define	ANIM_PATADA4		14
#define	ANIM_RISA		15
#define	ANIM_SIGILO		16
#define	ANIM_SIGILO2		17
#define	ANIM_ZOMBI		18
#define	ANIM_MOSQUEO		19
#define	ANIM_ANDAR3		20
#define	ANIM_CARGA		21
#define	ANIM_GRACIAS		22
#define	ANIM_PISOTON		23
#define	ANIM_GIRO		24
#define	ANIM_MOSQUEO2		25
#define	ANIM_GRITO		26
#define	ANIM_SALTO		27

#endif
