#ifndef __ANIM_ANMS_
#define __ANIM_ANMS_

#define FRAME0  1

#define	ANIM_GOLPE		0
#define	ANIM_ANDAR		1
#define	ANIM_ANDAR2		2
#define	ANIM_CORRER		3
#define	ANIM_DISPARO		4
#define	ANIM_AGACHAR		5
#define	ANIM_IMPACTO		6
#define	ANIM_IMPACTO2		7
#define	ANIM_MARCHA		8
#define	ANIM_MORTAL		9
#define	ANIM_MUERTE		10
#define	ANIM_NEGACION		11
#define	ANIM_PATADA		12
#define	ANIM_PATADA2		13
#define	ANIM_PATADA3		14
#define	ANIM_PATADA4		15
#define	ANIM_RISA		16
#define	ANIM_SIGILO		17
#define	ANIM_SIGILO2		18
#define	ANIM_ZOMBI		19
#define	ANIM_MOSQUEO		20
#define	ANIM_ANDAR3		21
#define	ANIM_PISOTON		22
#define	ANIM_GIRO		23
#define	ANIM_MOSQUEO2		24
#define	ANIM_GRITO		25
#define	ANIM_SALTO		26

#endif
